# Generated by Django 4.1 on 2022-11-09 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_profile_likes'),
        ('tour', '0007_alter_tour_latitude_alter_tour_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('tour_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour_application', to='tour.tour', verbose_name='투어')),
                ('user_id', models.ManyToManyField(related_name='tour_application', to='user.profile', verbose_name='투어참가유저')),
            ],
            options={
                'verbose_name': '투어신청서',
                'verbose_name_plural': '투어신청서',
                'db_table': 'tour_application',
            },
        ),
    ]
