# Generated by Django 4.1 on 2022-11-22 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour_application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tourapplication',
            name='user',
            field=models.ManyToManyField(related_name='tour_application', to=settings.AUTH_USER_MODEL, verbose_name='투어참가유저'),
        ),
    ]
