# Generated by Django 4.1.3 on 2022-11-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_application', '0002_alter_tourapplication_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourapplication',
            old_name='tour_id',
            new_name='tour',
        ),
        migrations.RenameField(
            model_name='tourapplication',
            old_name='user_id',
            new_name='user',
        ),
    ]
