# Generated by Django 4.1.2 on 2022-11-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_application', '0003_rename_tour_id_tourapplication_tour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourapplication',
            name='participants_on_site',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tourapplication',
            name='tour_finished',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
