# Generated by Django 4.1.3 on 2022-11-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, to='tour.tour'),
        ),
    ]
