# Generated by Django 4.1.3 on 2022-12-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TourTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("estimated", models.IntegerField()),
                ("participants", models.PositiveIntegerField()),
                ("start_place", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("checkpoints", models.TextField(blank=True, null=True)),
                ("description", models.TextField()),
            ],
        ),
    ]
