# Generated by Django 4.1.2 on 2022-11-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bookmarks',
            field=models.ManyToManyField(null=True, to='tour_theme.tourtheme'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(null=True, related_name='follow', to='tour_theme.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(null=True, related_name='follower', to='tour_theme.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(null=True, to='tour_theme.tour'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reputation',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
