# Generated by Django 4.1.3 on 2022-11-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tour_theme", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tourtheme",
            name="category",
        ),
    ]
