# Generated by Django 4.1.2 on 2022-11-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_theme', '0003_alter_profile_bookmarks_alter_profile_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourtheme',
            name='estimated',
            field=models.IntegerField(),
        ),
    ]
