# Generated by Django 4.1.2 on 2022-11-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_theme', '0005_tourtheme_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bookmarks',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
