# Generated by Django 4.1.2 on 2022-11-01 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('tour_theme', '0006_remove_profile_bookmarks_remove_profile_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourtheme',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.profile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
