# Generated by Django 4.1.2 on 2022-11-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_theme', '0007_alter_tourtheme_author_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourtheme',
            name='created',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
