# Generated by Django 4.1.2 on 2022-11-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_theme', '0009_tourtheme_checkpoints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
