# Generated by Django 4.1 on 2022-11-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourName', models.CharField(max_length=256, verbose_name='투어이름')),
                ('date', models.CharField(max_length=50, verbose_name='투어일시')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('thumbnail', models.URLField(verbose_name='썸네일')),
                ('description', models.TextField(verbose_name='투어설명')),
                ('participants', models.PositiveIntegerField(verbose_name='정원')),
                ('start_place', models.CharField(max_length=100, verbose_name='시작장소')),
                ('latitude', models.FloatField(verbose_name='시작장소 위도')),
                ('longitude', models.FloatField(verbose_name='시작장소 경도')),
            ],
            options={
                'verbose_name': '투어',
                'verbose_name_plural': '투어',
                'db_table': 'tour',
            },
        ),
    ]
