# Generated by Django 4.1 on 2022-11-02 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_likes'),
        ('tour_theme', '0008_alter_tourtheme_created'),
        ('tour', '0002_tour_profile_id_tour_themeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='profile_id',
            field=models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='생성유저'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='themeId',
            field=models.ForeignKey(db_column='theme_id', on_delete=django.db.models.deletion.CASCADE, to='tour_theme.tourtheme', verbose_name='테마이름'),
        ),
    ]
