# Generated by Django 4.1.3 on 2022-11-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_alter_tour_profile_id_alter_tour_themeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='participants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='start_place',
            field=models.CharField(default='', max_length=100),
        ),
    ]
