# Generated by Django 4.1.3 on 2022-11-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_tour_latitude_tour_longitude_tour_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='participants',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_place',
            field=models.CharField(max_length=100),
        ),
    ]
