# Generated by Django 4.1 on 2022-11-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_alter_tour_latitude_alter_tour_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='themeId',
            new_name='theme_id',
        ),
    ]
