# Generated by Django 4.1 on 2022-11-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_rename_themeid_tour_theme_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='latitude',
            field=models.FloatField(verbose_name='시작장소 위도'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='longitude',
            field=models.FloatField(verbose_name='시작장소 경도'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='participants',
            field=models.PositiveIntegerField(verbose_name='정원'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_place',
            field=models.CharField(max_length=100, verbose_name='시작장소'),
        ),
    ]
